### ISSUE TITLE
DB연결 Test가 잘 작동되지 않습니다.

### ISSUE THREAD

**Issue by kny2383** [yu-podong/study_management#1]
![image](https://user-images.githubusercontent.com/80757985/154025136-c55b9e4b-b936-4941-88d7-99b0fd2727c2.png)
-> planMapperTests.java 
여기서 testInsert()를 실행하였더니 아래와 같은 오류가 발생합니다.
![image](https://user-images.githubusercontent.com/80757985/154025376-ec7ea3e6-8305-4252-a515-592937c15df3.png)

![image](https://user-images.githubusercontent.com/80757985/154025453-935193bf-0238-4ccc-9fa0-2b103cb15b0e.png)
-> planMapper.java

![image](https://user-images.githubusercontent.com/80757985/154025565-f9257046-3517-4a5e-9b36-92eb7d1233fe.png)
-> planMapper.xml

![image](https://user-images.githubusercontent.com/80757985/154025701-58d65643-f50c-43db-8ed9-a9fee12ae62c.png)
->planService.java

![image](https://user-images.githubusercontent.com/80757985/154025786-15acb28e-6175-4aa0-8114-1a79fb4c739e.png)
->planServicelmpl.java

**Comment by yu-podong** [comment]
`com.study_management.domain > WeeklyPlanDTO`에서 아래 내용을 추가해보세요.
```
@Data
@AllArgsConstructor
@NoArgsConstructor
public class WeeklyPlanDTO {
  // some lines...
}
```

그리고, 혹시 insert 관련해서 `addAllAttributes`를 사용한 부분이 있나요?

**Comment by rkd11011** [comment]
planMapper.java랑 planService.java 에서 insert 라는 같은 이름의 함수가 동시에 언급됩니다.
예제에서도 이름이 같은 함수를 Mapper랑 Service 두 곳에서 모두 선언 하는 경우를 본적이 없습니다.
같은 이름의 함수가 다른 곳에서 두번 언급되서 자동 매핑 과정에서 오류가 발생했을 지도 모르겠습니다.
